# python train.py --STA_mode "S" --input_size 256 --batch_size 64 --epoch 30 --save_dir "/media/ubuntu/Data/Result/"
# python train.py --STA_mode "SA" --input_size 256 --batch_size 40 --epoch 30 --save_dir "/media/ubuntu/Data/Result/"
# python train.py --STA_mode "ST" --input_size 256 --batch_size 20 --epoch 30 --save_dir "/media/ubuntu/Data/Result/"
python gen_att.py --STA_mode "S" --input_size 256 --batch_size 550 --epoch 30 --Att_re_path "/media/ubuntu/Data/Result_crop/Att_30"
python gen_att.py --STA_mode "SA" --input_size 256 --batch_size 170 --epoch 30 --Att_re_path "/media/ubuntu/Data/Result_crop/Att_30"
python gen_att.py --STA_mode "ST" --input_size 256 --batch_size 500 --epoch 30 --Att_re_path "/media/ubuntu/Data/Result_crop/Att_30"